# Change these first
owner: Navadhiti # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Varitra
    url: https://varitra.com
  - name: BarefootEdu
    url: https://barefootedu.com
  - name: Navadhiti
    url: https://navadhiti.com
  - name: Karunodaya
    url: https://karunodaya.in/
  - name: DoxApply
    url: https://doxapply.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: webup.navadhiti.com
  # baseUrl: /your-repo-name
  logoUrl: https://www.navadhiti.com/assets/img/logo-small.svg
  name: WebUp
#   introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#   introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
